CREATE SEQUENCE SEQ_TASUNTO_id START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 1;

CREATE TABLE TASUNTO
(
   ID   			 DOUBLE        DEFAULT (NEXT VALUE FOR PUBLIC.SEQ_TASUNTO_id) NOT NULL,
   DESCRIPCION VARCHAR(100)  NOT NULL,
   IDTIPO    	 VARCHAR(15)   NOT NULL
);

COMMENT ON COLUMN TASUNTO.ID IS 'Identificador único de tipo de asunto';
COMMENT ON COLUMN TASUNTO.IDTIPO IS 'Naturaleza del juzgado, cada asunto puede ser de un tipo de los del juzgado ';
COMMENT ON COLUMN TASUNTO.DESCRIPCION IS 'Descripción del tipo de asunto';


ALTER TABLE TASUNTO
   ADD CONSTRAINT PK_TASUNTO
   PRIMARY KEY (ID);
   
CREATE INDEX IX_TASUNTO
   ON TASUNTO (ID ASC);
   
CREATE UNIQUE INDEX UK_TASUNTO
   ON TASUNTO (DESCRIPCION ASC);

Insert into TASUNTO (DESCRIPCION, IDTIPO) VALUES ('Procedimiento abreviado', 'Penal');
Insert into TASUNTO (DESCRIPCION, IDTIPO) VALUES ('Procedimiento de divorcio', 'Civil');
Insert into TASUNTO (DESCRIPCION, IDTIPO) VALUES ('Impuganción testamento', 'Decano');
Insert into TASUNTO (DESCRIPCION, IDTIPO) VALUES ('Recamación de cantidad', 'Penal');

drop table PUBLIC.TEXPEDIENTE;
drop sequence PUBLIC.SEQ_TEXPED_id;

CREATE SEQUENCE SEQ_TEXPED_id START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 1;

CREATE TABLE TEXPEDIENTE
(
   ID   			 DOUBLE        DEFAULT (NEXT VALUE FOR PUBLIC.SEQ_TEXPED_id) NOT NULL,
   DESCRIPCION VARCHAR(100)  NOT NULL
);

COMMENT ON TABLE TEXPEDIENTE IS 'Auxiliar para indicar si el expediente es solicitado por el interesado o por el juzgado';
COMMENT ON COLUMN TEXPEDIENTE.ID IS 'Identificador único de tipo de expediente';
COMMENT ON COLUMN TEXPEDIENTE.DESCRIPCION IS 'Descripción del tipo de expediente';


ALTER TABLE TEXPEDIENTE
   ADD CONSTRAINT PK_TEXPEDIENTE
   PRIMARY KEY (ID);
   
CREATE INDEX IX_TEXPEDIENTE
   ON TEXPEDIENTE (ID ASC);
   
CREATE UNIQUE INDEX UK_TEXPEDIENTE
   ON TEXPEDIENTE (DESCRIPCION ASC);
   
insert into TEXPEDIENTE (DESCRIPCION) VALUES ('Interesado');
insert into TEXPEDIENTE (DESCRIPCION) VALUES ('Turno');

